-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- *** RESET & SIMPLIFY: DROP EVERYTHING ***
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.proposals CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.portfolio_items CASCADE;
DROP TABLE IF EXISTS public.meetings CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;

-- Storage Bucket Setup (Idempotent)
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Policies for Storage
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Auth Upload" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'images' );
CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'images' AND auth.role() = 'authenticated' );

-- Drop Types (Cleanup)
DROP TYPE IF EXISTS public.academic_level CASCADE;
DROP TYPE IF EXISTS public.project_category CASCADE;
DROP TYPE IF EXISTS public.user_role CASCADE; 
DROP TYPE IF EXISTS public.project_status CASCADE;
DROP TYPE IF EXISTS public.proposal_status CASCADE;
DROP TYPE IF EXISTS public.meeting_status CASCADE;
DROP TYPE IF EXISTS public.transaction_type CASCADE;
DROP TYPE IF EXISTS public.transaction_status CASCADE;

-- Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'client' CHECK (role IN ('client', 'developer', 'admin')),
  status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('pending', 'approved', 'rejected', 'suspended')),
  avatar TEXT,
  university TEXT,
  bio TEXT,
  balance NUMERIC(10, 2) DEFAULT 0.00,
  location TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Projects Table
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID REFERENCES public.profiles(id) NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  requirements TEXT,
  budget NUMERIC(10, 2) NOT NULL,
  timeline TEXT NOT NULL,
  level TEXT NOT NULL CHECK (level IN ('Undergraduate', 'Masters', 'PhD', 'Professional')),
  category TEXT NOT NULL, 
  skills TEXT[] DEFAULT '{}',
  urgent BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'in_progress', 'completed')),
  flyer_url TEXT,
  location TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Proposals Table
CREATE TABLE IF NOT EXISTS public.proposals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE NOT NULL,
  developer_id UUID REFERENCES public.profiles(id) NOT NULL,
  cover_letter TEXT NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  timeline TEXT NOT NULL,
  status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'rejected')),
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Reviews Table
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES public.projects(id) NOT NULL,
  reviewer_id UUID REFERENCES public.profiles(id) NOT NULL,
  reviewee_id UUID REFERENCES public.profiles(id) NOT NULL,
  rating INT CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Meetings Table
CREATE TABLE IF NOT EXISTS public.meetings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  host_id UUID REFERENCES public.profiles(id) NOT NULL,
  attendee_id UUID REFERENCES public.profiles(id) NOT NULL,
  title TEXT NOT NULL,
  start_time TIMESTAMPTZ NOT NULL,
  duration_minutes INT DEFAULT 30,
  status TEXT DEFAULT 'scheduled' CHECK (status IN ('scheduled', 'completed', 'cancelled')),
  link TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Messages Table
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES public.profiles(id) NOT NULL,
  receiver_id UUID REFERENCES public.profiles(id) NOT NULL,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Transactions Table
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  amount NUMERIC(10, 2) NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('credit', 'debit')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'completed', 'failed')),
  reference TEXT UNIQUE,
  description TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Portfolio Items Table (Missing in previous context but good to have if referenced)
CREATE TABLE IF NOT EXISTS public.portfolio_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  title TEXT NOT NULL,
  description TEXT,
  image_urls TEXT[], 
  link TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.proposals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.meetings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_items ENABLE ROW LEVEL SECURITY;

-- --- Policies ---

-- Profiles
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
-- Admin can update any profile (e.g. approve/reject)
CREATE POLICY "Admins can update any profile" ON public.profiles FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Projects
CREATE POLICY "Public projects are viewable by everyone" ON public.projects FOR SELECT USING (true);
CREATE POLICY "Clients can create projects" ON public.projects FOR INSERT WITH CHECK (auth.uid() = client_id);
CREATE POLICY "Clients can update own projects" ON public.projects FOR UPDATE USING (auth.uid() = client_id);

-- Proposals
CREATE POLICY "Developers can create proposals" ON public.proposals FOR INSERT WITH CHECK (auth.uid() = developer_id);
CREATE POLICY "Users can view proposals" ON public.proposals FOR SELECT USING (true); 

-- Messages
CREATE POLICY "Users can view their own messages" ON public.messages 
  FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY "Users can send messages" ON public.messages 
  FOR INSERT WITH CHECK (auth.uid() = sender_id);
CREATE POLICY "Recipients can mark messages as read" ON public.messages 
  FOR UPDATE USING (auth.uid() = receiver_id);

-- Transactions
CREATE POLICY "Users can view their own transactions" ON public.transactions
  FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert own transactions" ON public.transactions
    FOR INSERT WITH CHECK (auth.uid() = user_id);
-- Admin can view ALL transactions
CREATE POLICY "Admins can view all transactions" ON public.transactions
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Portfolio
CREATE POLICY "Public portfolio items are viewable by everyone" ON public.portfolio_items FOR SELECT USING (true);
CREATE POLICY "Users can manage own portfolio" ON public.portfolio_items FOR ALL USING (auth.uid() = user_id);

-- --- Functions & Triggers ---

-- Handle New User Signup
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
DECLARE
  v_role TEXT;
  v_status TEXT;
BEGIN
  v_role := COALESCE(new.raw_user_meta_data->>'role', 'client');
  
  -- Determine Initial Status
  IF v_role = 'developer' THEN
    v_status := 'pending';
  ELSE
    v_status := 'approved'; -- Clients and Admins auto-approved
  END IF;

  INSERT INTO public.profiles (id, name, email, role, status, avatar, university, location)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'name', 'New User'), 
    new.email, 
    v_role,
    v_status, -- Set status
    new.raw_user_meta_data->>'avatar',
    new.raw_user_meta_data->>'university',
    new.raw_user_meta_data->>'location'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
 
 - -   O p t i m i z e d   A d m i n   S t a t s   F u n c t i o n  
 C R E A T E   O R   R E P L A C E   F U N C T I O N   p u b l i c . g e t _ a d m i n _ d a s h b o a r d _ s t a t s ( )  
 R E T U R N S   J S O N B   A S   $ $  
 D E C L A R E  
     v _ c l i e n t _ c o u n t   I N T ;  
     v _ d e v e l o p e r _ c o u n t   I N T ;  
     v _ p e n d i n g _ c o u n t   I N T ;  
     v _ t o t a l _ v o l u m e   N U M E R I C ;  
 B E G I N  
     - -   C h e c k   i f   u s e r   i s   a d m i n  
     I F   N O T   E X I S T S   ( S E L E C T   1   F R O M   p u b l i c . p r o f i l e s   W H E R E   i d   =   a u t h . u i d ( )   A N D   r o l e   =   ' a d m i n ' )   T H E N  
         R A I S E   E X C E P T I O N   ' A c c e s s   D e n i e d ' ;  
     E N D   I F ;  
  
     - -   G e t   C o u n t s  
     S E L E C T   C O U N T ( * )   I N T O   v _ c l i e n t _ c o u n t   F R O M   p u b l i c . p r o f i l e s   W H E R E   r o l e   =   ' c l i e n t ' ;  
     S E L E C T   C O U N T ( * )   I N T O   v _ d e v e l o p e r _ c o u n t   F R O M   p u b l i c . p r o f i l e s   W H E R E   r o l e   =   ' d e v e l o p e r ' ;  
     S E L E C T   C O U N T ( * )   I N T O   v _ p e n d i n g _ c o u n t   F R O M   p u b l i c . p r o f i l e s   W H E R E   s t a t u s   =   ' p e n d i n g ' ;  
      
     - -   G e t   V o l u m e   ( S u m )  
     S E L E C T   C O A L E S C E ( S U M ( a m o u n t ) ,   0 )   I N T O   v _ t o t a l _ v o l u m e   F R O M   p u b l i c . t r a n s a c t i o n s ;  
  
     R E T U R N   j s o n b _ b u i l d _ o b j e c t (  
         ' c l i e n t C o u n t ' ,   v _ c l i e n t _ c o u n t ,  
         ' d e v e l o p e r C o u n t ' ,   v _ d e v e l o p e r _ c o u n t ,  
         ' p e n d i n g C o u n t ' ,   v _ p e n d i n g _ c o u n t ,  
         ' t o t a l V o l u m e ' ,   v _ t o t a l _ v o l u m e  
     ) ;  
 E N D ;  
 $ $   L A N G U A G E   p l p g s q l   S E C U R I T Y   D E F I N E R ;  
 