-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- *** RESET & SIMPLIFY: DROP EVERYTHING ***
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
DROP FUNCTION IF EXISTS public.handle_new_user();
DROP TABLE IF EXISTS public.transactions CASCADE;
DROP TABLE IF EXISTS public.reviews CASCADE;
DROP TABLE IF EXISTS public.proposals CASCADE; -- Removing Marketplace Artifact
DROP TABLE IF EXISTS public.qa_logs CASCADE;
DROP TABLE IF EXISTS public.tasks CASCADE;
DROP TABLE IF EXISTS public.projects CASCADE;
DROP TABLE IF EXISTS public.profiles CASCADE;
DROP TABLE IF EXISTS public.portfolio_items CASCADE;
DROP TABLE IF EXISTS public.meetings CASCADE;
DROP TABLE IF EXISTS public.messages CASCADE;

-- Storage Bucket Setup (Idempotent)
INSERT INTO storage.buckets (id, name, public)
VALUES ('images', 'images', true)
ON CONFLICT (id) DO NOTHING;

-- Policies for Storage
DROP POLICY IF EXISTS "Public Access" ON storage.objects;
DROP POLICY IF EXISTS "Auth Upload" ON storage.objects;

CREATE POLICY "Public Access" ON storage.objects FOR SELECT USING ( bucket_id = 'images' );
CREATE POLICY "Auth Upload" ON storage.objects FOR INSERT WITH CHECK ( bucket_id = 'images' AND auth.role() = 'authenticated' );

-- Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  role TEXT NOT NULL DEFAULT 'client' CHECK (role IN ('client', 'developer', 'admin')),
  status TEXT NOT NULL DEFAULT 'approved' CHECK (status IN ('pending', 'approved', 'rejected', 'suspended', 'onboarding')),
  avatar TEXT,
  university TEXT,
  bio TEXT,
  location TEXT,
  
  -- Managed Network Fields
  internal_rating NUMERIC(2, 1) DEFAULT 0.0,
  hourly_rate NUMERIC(10, 2),
  vetting_status TEXT DEFAULT 'new' CHECK (vetting_status IN ('new', 'interviewing', 'verified', 'probation', 'gold')),
  public_alias TEXT, -- For masked display
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Projects Table (Client Requests)
CREATE TABLE IF NOT EXISTS public.projects (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_id UUID REFERENCES public.profiles(id) NOT NULL,
  manager_id UUID REFERENCES public.profiles(id), -- Admin Project Manager
  
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  requirements TEXT,
  budget NUMERIC(10, 2) NOT NULL,
  escrow_balance NUMERIC(10, 2) DEFAULT 0.00, -- Funds held for project
  total_paid NUMERIC(10, 2) DEFAULT 0.00,   -- Funds already paid out
  timeline TEXT NOT NULL,
  level TEXT CHECK (level IN ('Undergraduate', 'Masters', 'PhD', 'Professional')),
  category TEXT NOT NULL, 
  skills TEXT[] DEFAULT '{}',
  urgent BOOLEAN DEFAULT FALSE,
  status TEXT DEFAULT 'requested' CHECK (status IN ('requested', 'scoping', 'active', 'review', 'completed', 'cancelled')),
  flyer_url TEXT,
  location TEXT,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Tasks Table (Internal Work Units)
CREATE TABLE IF NOT EXISTS public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id BIGINT REFERENCES public.projects(id) ON DELETE CASCADE NOT NULL,
  assignee_id UUID REFERENCES public.profiles(id), -- Developer
  
  title TEXT NOT NULL,
  description TEXT NOT NULL, -- Technical Instructions
  status TEXT DEFAULT 'open' CHECK (status IN ('open', 'assigned', 'in_progress', 'qa_ready', 'completed', 'blocked')),
  
  budget_payout NUMERIC(10, 2) NOT NULL, -- Developer Pay
  due_date TIMESTAMPTZ,
  
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- QA Logs
CREATE TABLE IF NOT EXISTS public.qa_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES public.tasks(id) ON DELETE CASCADE NOT NULL,
  reviewer_id UUID REFERENCES public.profiles(id) NOT NULL,
  status TEXT CHECK (status IN ('pass', 'fail', 'warning')),
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Messages (Internal Only)
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sender_id UUID REFERENCES public.profiles(id) NOT NULL,
  receiver_id UUID REFERENCES public.profiles(id) NOT NULL,
  project_id BIGINT REFERENCES public.projects(id),
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE,
  is_internal BOOLEAN DEFAULT FALSE, -- Internal team comms
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Transactions
CREATE TABLE IF NOT EXISTS public.transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  type TEXT CHECK (type IN ('credit', 'debit')),
  category TEXT CHECK (category IN ('deposit', 'payout', 'refund', 'fee')),
  amount NUMERIC(10, 2) NOT NULL,
  description TEXT,
  status TEXT DEFAULT 'pending',
  
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Portfolio
CREATE TABLE IF NOT EXISTS public.portfolio_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  image_urls TEXT[],
  link TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);


-- Enable RLS
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.projects ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qa_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_items ENABLE ROW LEVEL SECURITY;

-- --- Policies ---

-- Profiles
CREATE POLICY "Public profiles are viewable by everyone" ON public.profiles FOR SELECT USING (true);
CREATE POLICY "Users can insert their own profile" ON public.profiles FOR INSERT WITH CHECK (auth.uid() = id);
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);
-- Admin can update any profile
CREATE POLICY "Admins can update any profile" ON public.profiles FOR UPDATE USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Projects: STRICT ISOLATION
-- Admin: See All
CREATE POLICY "Admins see all projects" ON public.projects FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
-- Client: See Own Only
CREATE POLICY "Clients see own projects" ON public.projects FOR SELECT USING (
  auth.uid() = client_id
);
-- Client: Create
CREATE POLICY "Clients can create projects" ON public.projects FOR INSERT WITH CHECK (auth.uid() = client_id);

-- Tasks: THE WALL
-- Admin: Full Access
CREATE POLICY "Admins full access tasks" ON public.tasks FOR ALL USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
);
-- Developer: See Assigned Only
CREATE POLICY "Developers see assigned tasks" ON public.tasks FOR SELECT USING (
  auth.uid() = assignee_id
);
-- Developer: Update Assigned (Status only ideally, but permissive for now)
CREATE POLICY "Developers update assigned tasks" ON public.tasks FOR UPDATE USING (
  auth.uid() = assignee_id
);

-- Messages
CREATE POLICY "Users can view their own messages" ON public.messages 
  FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);
CREATE POLICY "Users can send messages" ON public.messages 
  FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- Transactions
CREATE POLICY "Users can view their own transactions" ON public.transactions
  FOR SELECT USING (auth.uid() = user_id);
-- Admin view ALL
CREATE POLICY "Admins can view all transactions" ON public.transactions
  FOR SELECT USING (
  EXISTS (SELECT 1 FROM public.profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- Portfolio
CREATE POLICY "Public portfolio" ON public.portfolio_items FOR SELECT USING (true);
CREATE POLICY "Users manage portfolio" ON public.portfolio_items FOR ALL USING (auth.uid() = user_id);

-- --- Functions & Triggers ---

CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
DECLARE
  v_role TEXT;
  v_status TEXT;
BEGIN
  v_role := COALESCE(new.raw_user_meta_data->>'role', 'client');
  
  -- Determine Initial Status
  IF v_role = 'developer' THEN
    v_status := 'onboarding';
  ELSE
    v_status := 'approved';
  END IF;

  INSERT INTO public.profiles (id, name, email, role, status, avatar, university, location)
  VALUES (
    new.id, 
    COALESCE(new.raw_user_meta_data->>'name', 'New User'), 
    new.email, 
    v_role,
    v_status,
    new.raw_user_meta_data->>'avatar',
    new.raw_user_meta_data->>'university',
    new.raw_user_meta_data->>'location'
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
